// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lottery/lottery/lottery.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Lottery struct {
	Id         uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StartBlock int64      `protobuf:"varint,2,opt,name=start_block,json=startBlock,proto3" json:"start_block,omitempty"`
	EndBlock   int64      `protobuf:"varint,3,opt,name=end_block,json=endBlock,proto3" json:"end_block,omitempty"`
	BetCount   uint64     `protobuf:"varint,4,opt,name=bet_count,json=betCount,proto3" json:"bet_count,omitempty"`
	WinnerId   string     `protobuf:"bytes,5,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	Payout     types.Coin `protobuf:"bytes,6,opt,name=payout,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coin" json:"payout"`
}

func (m *Lottery) Reset()         { *m = Lottery{} }
func (m *Lottery) String() string { return proto.CompactTextString(m) }
func (*Lottery) ProtoMessage()    {}
func (*Lottery) Descriptor() ([]byte, []int) {
	return fileDescriptor_2afbd19f2e624dbf, []int{0}
}
func (m *Lottery) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Lottery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Lottery.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Lottery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lottery.Merge(m, src)
}
func (m *Lottery) XXX_Size() int {
	return m.Size()
}
func (m *Lottery) XXX_DiscardUnknown() {
	xxx_messageInfo_Lottery.DiscardUnknown(m)
}

var xxx_messageInfo_Lottery proto.InternalMessageInfo

func (m *Lottery) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Lottery) GetStartBlock() int64 {
	if m != nil {
		return m.StartBlock
	}
	return 0
}

func (m *Lottery) GetEndBlock() int64 {
	if m != nil {
		return m.EndBlock
	}
	return 0
}

func (m *Lottery) GetBetCount() uint64 {
	if m != nil {
		return m.BetCount
	}
	return 0
}

func (m *Lottery) GetWinnerId() string {
	if m != nil {
		return m.WinnerId
	}
	return ""
}

func (m *Lottery) GetPayout() types.Coin {
	if m != nil {
		return m.Payout
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Lottery)(nil), "vjdmhd.lottery.lottery.Lottery")
}

func init() { proto.RegisterFile("lottery/lottery/lottery.proto", fileDescriptor_2afbd19f2e624dbf) }

var fileDescriptor_2afbd19f2e624dbf = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xc1, 0x4e, 0x32, 0x31,
	0x14, 0x85, 0xa7, 0xc0, 0xcf, 0x0f, 0x25, 0x71, 0x31, 0x31, 0x66, 0xc4, 0x58, 0x26, 0x6e, 0x1c,
	0x17, 0xb6, 0x41, 0xdf, 0x00, 0x56, 0x26, 0xae, 0x66, 0xe9, 0x86, 0x4c, 0xa7, 0x0d, 0x54, 0xa0,
	0x97, 0x4c, 0x0b, 0xca, 0x5b, 0xf8, 0x1c, 0x3e, 0x09, 0x4b, 0x96, 0xae, 0xd4, 0xc0, 0x33, 0xb8,
	0x37, 0xd3, 0x8e, 0xc4, 0xb8, 0x3a, 0x77, 0xce, 0xb9, 0xf3, 0x25, 0xe7, 0x16, 0x9f, 0xcf, 0xc0,
	0x5a, 0x59, 0xac, 0xd9, 0x1f, 0xa5, 0x8b, 0x02, 0x2c, 0x84, 0x27, 0xab, 0x47, 0x31, 0x9f, 0x08,
	0xfa, 0xe3, 0x56, 0xda, 0x3d, 0x1e, 0xc3, 0x18, 0xdc, 0x0a, 0x2b, 0x27, 0xbf, 0xdd, 0x25, 0x39,
	0x98, 0x39, 0x18, 0xc6, 0x33, 0x23, 0xd9, 0xaa, 0xcf, 0xa5, 0xcd, 0xfa, 0x2c, 0x07, 0xa5, 0x7d,
	0x7e, 0xf1, 0x85, 0xf0, 0xff, 0x7b, 0x4f, 0x08, 0x8f, 0x70, 0x4d, 0x89, 0x08, 0xc5, 0x28, 0x69,
	0xa4, 0x35, 0x25, 0xc2, 0x1e, 0xee, 0x18, 0x9b, 0x15, 0x76, 0xc4, 0x67, 0x90, 0x4f, 0xa3, 0x5a,
	0x8c, 0x92, 0x7a, 0x8a, 0x9d, 0x35, 0x28, 0x9d, 0xf0, 0x0c, 0xb7, 0xa5, 0x16, 0x55, 0x5c, 0x77,
	0x71, 0x4b, 0x6a, 0x71, 0x08, 0xb9, 0xb4, 0xa3, 0x1c, 0x96, 0xda, 0x46, 0x0d, 0x07, 0x6d, 0x71,
	0x69, 0x87, 0xe5, 0x77, 0x19, 0x3e, 0x29, 0xad, 0x65, 0x31, 0x52, 0x22, 0xfa, 0x17, 0xa3, 0xa4,
	0x9d, 0xb6, 0xbc, 0x71, 0x27, 0x42, 0x8e, 0x9b, 0x8b, 0x6c, 0x0d, 0x4b, 0x1b, 0x35, 0x63, 0x94,
	0x74, 0x6e, 0x4e, 0xa9, 0x2f, 0x41, 0xcb, 0x12, 0xb4, 0x2a, 0x41, 0x87, 0xa0, 0xf4, 0x80, 0x6d,
	0xde, 0x7b, 0xc1, 0xeb, 0x47, 0xef, 0x72, 0xac, 0xec, 0x64, 0xc9, 0x69, 0x0e, 0x73, 0x56, 0x35,
	0xf6, 0x72, 0x6d, 0xc4, 0x94, 0xd9, 0xf5, 0x42, 0x1a, 0xf7, 0x43, 0x5a, 0x91, 0x07, 0xc3, 0xcd,
	0x8e, 0xa0, 0xed, 0x8e, 0xa0, 0xcf, 0x1d, 0x41, 0x2f, 0x7b, 0x12, 0x6c, 0xf7, 0x24, 0x78, 0xdb,
	0x93, 0xe0, 0xe1, 0xea, 0x17, 0xca, 0x9f, 0xfa, 0xf0, 0x10, 0xcf, 0x87, 0xc9, 0x11, 0x79, 0xd3,
	0xdd, 0xf0, 0xf6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x21, 0x62, 0xf8, 0xb2, 0x01, 0x00, 0x00,
}

func (m *Lottery) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Lottery) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Lottery) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Payout.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintLottery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.WinnerId) > 0 {
		i -= len(m.WinnerId)
		copy(dAtA[i:], m.WinnerId)
		i = encodeVarintLottery(dAtA, i, uint64(len(m.WinnerId)))
		i--
		dAtA[i] = 0x2a
	}
	if m.BetCount != 0 {
		i = encodeVarintLottery(dAtA, i, uint64(m.BetCount))
		i--
		dAtA[i] = 0x20
	}
	if m.EndBlock != 0 {
		i = encodeVarintLottery(dAtA, i, uint64(m.EndBlock))
		i--
		dAtA[i] = 0x18
	}
	if m.StartBlock != 0 {
		i = encodeVarintLottery(dAtA, i, uint64(m.StartBlock))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintLottery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLottery(dAtA []byte, offset int, v uint64) int {
	offset -= sovLottery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Lottery) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovLottery(uint64(m.Id))
	}
	if m.StartBlock != 0 {
		n += 1 + sovLottery(uint64(m.StartBlock))
	}
	if m.EndBlock != 0 {
		n += 1 + sovLottery(uint64(m.EndBlock))
	}
	if m.BetCount != 0 {
		n += 1 + sovLottery(uint64(m.BetCount))
	}
	l = len(m.WinnerId)
	if l > 0 {
		n += 1 + l + sovLottery(uint64(l))
	}
	l = m.Payout.Size()
	n += 1 + l + sovLottery(uint64(l))
	return n
}

func sovLottery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLottery(x uint64) (n int) {
	return sovLottery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Lottery) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLottery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Lottery: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Lottery: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartBlock", wireType)
			}
			m.StartBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndBlock", wireType)
			}
			m.EndBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BetCount", wireType)
			}
			m.BetCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BetCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WinnerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLottery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLottery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WinnerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLottery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLottery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Payout.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLottery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLottery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLottery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLottery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLottery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLottery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLottery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLottery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLottery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLottery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLottery = fmt.Errorf("proto: unexpected end of group")
)
