version: 1
accounts:
  - name: alice
    coins: ["500000000utoken", "200000000stake"]
  - name: bob
    coins: ["500000000utoken", "100000000stake"]
validators:
  - name: alice
    bonded: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5000000utoken", "100000stake"]
genesis:
  app_state:
    lottery: 
      params: 
        lottery_fee: "5000000"
        bet_size:
          min_bet: "1000000"
          max_bet: "100000000"
